### ISSUE TITLE
sensor.hko_forecast_summary shows unknown

### ISSUE THREAD

**Issue by AzNdevil** [aes-alienrip/hko-weather-card#5]
rest state has a max char limit of 255...
should be able to workaround this if the summaries are stored as an attribute per below link?
[https://community.home-assistant.io/t/wth-is-255-the-max-length-for-states/471178/3](url)

2023-10-07 19:43:49.660 ERROR (MainThread) [homeassistant.helpers.entity] Failed to set state, fall back to unknown
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 906, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1687, in async_set
    state = State(
            ^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1264, in __init__
    validate_state(state)
  File "/usr/src/homeassistant/homeassistant/core.py", line 184, in validate_state
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state with length 283. State max length is 255 characters.

**Comment by aes-alienrip** [comment]
Thanks for report
1.1.9a should fix the only state of sensor may exceed the 255 characters max length limit

**Comment by AzNdevil** [comment]
good job! thanks for the fix!

**Comment by AzNdevil** [comment]
good thanks for the fix, but for some reason its not working on chrome dev or chrome canary
its showing fine on edge though

**Comment by aes-alienrip** [comment]
> good thanks for the fix, but for some reason its not working on chrome dev or chrome canary its showing fine on edge though

l tried chrome dev and canary on android both show the card normally
